import { BarrackId, BulletId, CastingId, SpellId, WarriorId } from "./ids";
import { ArmorType, AttackType, BulletType, CastingType, SpellType, WarriorType } from "../../constants";
import { IGameConfig } from "./game-config.interface";

export const defaultGameConfig: IGameConfig = {
  warriors: [
    {
      price: 10,
      id: WarriorId.SwordMan,
      armor: 5,
      armorType: ArmorType.Heavy,
      attackRange: 20,
      type: WarriorType.Warrior,
      attackMin: 30,
      attackMax: 44,
      radius: 10,
      healthMax: 160,
      movementSpeed: 30,
      attackType: AttackType.Sword,
      spellsOnDamage: [
        {
          chance: 0.5,
          spell: {
            id: SpellId.Stun,
            type: SpellType.Stun,
            timePoints: [10],
            duration: 2000,
          },
        },
      ],
      splash: {
        factor: 0.3,
        radius: 20,
      },
      attackTiming: {
        preAction: 800,
        completeAction: 1200,
        rollback: 0,
      },
    },
    {
      price: 10,
      id: WarriorId.DarkWizard,
      armor: 5,
      armorType: ArmorType.Heavy,
      attackRange: 40,
      type: WarriorType.Warrior,
      attackMin: 30,
      attackMax: 44,
      radius: 10,
      healthMax: 160,
      movementSpeed: 30,
      attackType: AttackType.Magic,
      attackTiming: {
        preAction: 900,
        completeAction: 1200,
        rollback: 0,
      },
      castings: [
        {
          id: CastingId.WizardDamageSpell,
          type: CastingType.Base,
          range: 100,
          timing: {
            preAction: 800,
            completeAction: 1200,
            rollback: 15e3,
          },
          spells: [
            {
              id: SpellId.WizardSpell,
              type: SpellType.SplashSpells,
              splashRadius: 50,
              splashSpells: [
                {
                  id: SpellId.WizardSpell,
                  type: SpellType.Damage,
                  attackType: AttackType.Magic,
                  attack: 100,
                  timePoints: [10],
                  duration: 100,
                },
                {
                  id: SpellId.Stun,
                  type: SpellType.Stun,
                  timePoints: [10],
                  duration: 4000,
                },
              ],
              timePoints: [10],
              duration: 700,
            },
            {
              id: SpellId.Stun,
              type: SpellType.Stun,
              timePoints: [10],
              duration: 4000,
            },
          ],
        },
      ],
    },
    {
      price: 10,
      id: WarriorId.Bowman,
      armor: 5,
      armorType: ArmorType.Light,
      attackRange: 130,
      type: WarriorType.Warrior,
      attackMin: 30,
      attackMax: 44,
      attackType: AttackType.Arrow,
      attackTiming: {
        preAction: 1000,
        completeAction: 1400,
        rollback: 0,
      },
      bullet: {
        id: BulletId.Arrow,
        radius: 10,
        type: BulletType.Base,
        movementSpeed: 450,
      },
      radius: 10,
      healthMax: 140,
      movementSpeed: 30,
      spellsOnDamage: [
        {
          spell: {
            id: SpellId.Stun,
            type: SpellType.Stun,
            attack: 20,
            attackType: AttackType.Magic,
            duration: 700,
            timePoints: [10],
          },
          chance: 0.3,
        },
      ],
    },
    {
      price: 10,
      id: WarriorId.FireWorm,
      armor: 2,
      armorType: ArmorType.Heavy,
      attackRange: 130,
      type: WarriorType.Warrior,
      attackMin: 40,
      attackMax: 54,
      attackType: AttackType.Sword,
      attackTiming: {
        preAction: 1000,
        completeAction: 1400,
        rollback: 0,
      },
      bullet: {
        id: BulletId.FireWormBall,
        radius: 10,
        type: BulletType.Base,
        movementSpeed: 250,
      },
      radius: 10,
      healthMax: 180,
      movementSpeed: 30,
    },
    {
      price: 10,
      id: WarriorId.Catapult,
      armor: 5,
      magicResistance: true,
      armorType: ArmorType.Building,
      attackRange: 150,
      type: WarriorType.Warrior,
      attackMin: 60,
      attackMax: 64,
      attackType: AttackType.Siege,
      radius: 10,
      healthMax: 140,
      movementSpeed: 30,
      splash: {
        radius: 30,
        factor: 0.3,
      },
      attackTiming: {
        preAction: 800,
        completeAction: 2000,
        rollback: 0,
      },
      bullet: {
        id: BulletId.CatapultStone,
        radius: 10,
        type: BulletType.Base,
        movementSpeed: 130,
      },
    },
    {
      price: 10,
      id: WarriorId.Wizard,
      armor: 5,
      armorType: ArmorType.Magic,
      attackRange: 150,
      type: WarriorType.Warrior,
      attackMin: 30,
      attackMax: 34,
      attackType: AttackType.Magic,
      radius: 10,
      healthMax: 100,
      movementSpeed: 30,
      attackTiming: {
        preAction: 1200,
        completeAction: 1600,
        rollback: 0,
      },
      bullet: {
        id: BulletId.WizardFileBall,
        radius: 10,
        type: BulletType.Base,
        movementSpeed: 180,
      },
      castings: [
        {
          id: CastingId.WizardDamageSpell,
          type: CastingType.Base,
          range: 200,
          timing: {
            preAction: 800,
            completeAction: 1200,
            rollback: 5e3,
          },
          spells: [
            {
              id: SpellId.WizardSpell,
              type: SpellType.Damage,
              attackType: AttackType.Magic,
              attack: 100,
              timePoints: [10],
              duration: 100,
            },
          ],
        },
      ],
    },
    {
      price: 300,
      id: WarriorId.Castle,
      armor: 15,
      magicResistance: true,
      armorType: ArmorType.Building,
      attackRange: 200,
      type: WarriorType.Tower,
      attackMin: 150,
      attackMax: 230,
      attackType: AttackType.Siege,
      attackTiming: {
        preAction: 800,
        completeAction: 1000,
        rollback: 0,
      },
      bullet: {
        id: BulletId.CastleBullet,
        radius: 10,
        type: BulletType.Base,
        movementSpeed: 200,
      },
      splash: {
        radius: 30,
        factor: 0.3,
      },
      radius: 10,
      healthMax: 160,
      movementSpeed: 0,
    },
  ],
  barracks: [
    {
      id: BarrackId.CatapultBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.Catapult],
    },
    {
      id: BarrackId.DarkWizardBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.DarkWizard],
    },
    {
      id: BarrackId.FireWormBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.FireWorm],
    },
    {
      id: BarrackId.WizardBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.Wizard],
    },
    {
      id: BarrackId.BowmanBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.Bowman],
    },
    {
      id: BarrackId.SwordsmanBarrack,
      level: 1,
      price: 500,
      warriorIds: [WarriorId.SwordMan],
    },
  ],
};
